const PROFESSIONS = [
  "Photographer",
  "Painter",
  "Musician",
  "Dancer",
  "Sketch Artist",
  "Guitarist",
  "Violinist",
  "Pianist",
  "Actor",
  "Writer",
  "Poet",
  "Calligrapher",
  "Sculptor",
  "Tattoo Artist",
  "Graphic Designer",
  "Fashion Designer",
  "Interior Designer",
  "Animator",
  "Filmmaker",
  "Theater Artist",
  "Digital Artist",
  "Classical Dancer",
  "Rangoli Artist",
  "Mehndi Artist",
  "Warli Painter",
  "Madhubani Painter",
  "Jewelry Designer",
  "Terracotta Artist",
  "Potter",
  "Makeup Artist",
  "Set Designer",
  "Voice Actor",
  "Storyteller",
  "Illustrator",
  "Handloom Weaver",
  "Screenwriter",
  "Art Director",
  "Art Curator",
  "Art Restorer",
  "Art Therapist",
  "Ceramic Artist",
  "Glass Artist",
  "Muralist",
  "Printmaker",
  "Etcher",
  "Lino Cutter",
  "Collage Artist",
  "Quilling Artist",
  "Batik Artist",
  "Encaustic Painter",
  "Sumi-e Artist",
  "Landscape Painter",
  "Portrait Painter",
  "Abstract Painter",
  "Pop Artist",
  "Surrealist",
  "Impressionist",
  "Watercolor Artist",
  "Oil Painter",
  "Acrylic Painter",
  "Charcoal Artist",
  "Pastel Artist",
  "Mosaic Artist",
  "Stained Glass Artist",
  "Metal Sculptor",
  "Wood Carver",
  "Textile Designer",
  "Concept Artist",
  "Character Designer",
  "Comic Book Artist",
  "Storyboard Artist",
  "Performance Artist",
  "Installation Artist",
  "Interactive Artist",
  "Kinetic Artist",
  "Sand Artist",
  "Ice Sculptor",
  "Lighting Designer",
  "Costume Designer",
  "Props Master",
  "Special Effects Artist",
  "Sound Designer",
  "Film Editor",
  "Cinematographer",
  "Production Designer",
  "Stage Manager",
  "Event Planner",
  "Creative Director",
  "Advertising Copywriter",
  "Branding Specialist",
  "UI/UX Designer",
  "Game Designer",
  "3D Modeler",
  "VFX Artist",
  "Stop Motion Animator",
  "Motion Graphics Designer",
  "Typography Designer",
  "Logo Designer",
  "Packaging Designer",
  "Pattern Designer",
  "Embroidery Artist",
  "Block Printer",
  "Weaving Artist",
  "Fiber Artist",
  "Leather Artisan",
  "Paper Marbling Artist",
  "Bookbinder",
  "Calligraphy Instructor",
  "Art Teacher",
  "Art Critic",
  "Gallery Owner",
  "Museum Curator",
  "Architect",
  "Landscape Architect",
  "Industrial Designer",
  "Product Designer",
  "Automotive Designer",
  "Footwear Designer",
  "Accessory Designer",
  "Cosplay Designer",
  "Body Painter",
  "Projection Artist",
  "Holography Artist",
  "Virtual Reality Designer",
  "Augmented Reality Designer",
  "Street Performer",
  "Magician",
  "Puppeteer",
  "Shadow Puppet Artist",
  "Fire Performer",
  "Aerialist",
  "Circus Artist",
  "Clown",
  "DJ",
  "Composer",
  "Lyricist",
  "Songwriter",
  "Sound Engineer",
  "Recording Artist",
  "Music Producer",
  "Band Member",
  "Orchestra Member",
  "Choreographer",
  "Dance Instructor",
  "Yoga Instructor",
  "Pilates Instructor",
  "Fitness Instructor",
  "Zumba Instructor",
  "Ballet Instructor",
  "Hip-Hop Instructor",
  "Contemporary Dance Instructor",
  "Kathak Instructor",
  "Bharatanatyam Instructor",
  "Odissi Instructor",
  "Kuchipudi Instructor",
  "Mohiniyattam Instructor",
  "Sattriya Instructor",
  "Manipuri Dance Instructor",
  "Folk Dance Instructor",
  "Classical Music Instructor",
  "Carnatic Music Instructor",
  "Hindustani Music Instructor",
  "Flute Instructor",
  "Guitar Instructor",
  "Violin Instructor",
  "Piano Instructor",
  "Drum Instructor",
  "Tabla Instructor",
  "Sitar Instructor",
  "Sarod Instructor",
  "Harmonium Instructor",
  "Vocal Coach",
  "Opera Singer",
  "Choir Conductor",
  "Music Therapist",
  "Artisan",
  "Craftsperson",
  "Restoration Specialist",
  "Conservationist",
  "Historian",
  "Cultural Ambassador",
  "Ethnomusicologist",
  "Ethnographer",
  "Art Historian",
  "Visual Anthropologist",
  "Others"
];

export default PROFESSIONS;
