const INTERESTS = [
  "Photography",
  "Painting",
  "Music",
  "Dancing",
  "Sketching",
  "Guitar",
  "Violin",
  "Piano",
  "Acting",
  "Writing",
  "Poetry",
  "Calligraphy",
  "Sculpting",
  "Tattoo Art",
  "Graphic Design",
  "Fashion Design",
  "Interior Design",
  "Animation",
  "Film Making",
  "Theater",
  "Digital Art",
  "Bharatanatyam",
  "Kathak",
  "Odissi",
  "Kuchipudi",
  "Mohiniyattam",
  "Sattriya",
  "Manipuri Dance",
  "Folk Dance",
  "Classical Music",
  "Carnatic Music",
  "Hindustani Music",
  "Rangoli Art",
  "Mehndi Art",
  "Warli Painting",
  "Madhubani Painting",
  "Tanjore Painting",
  "Pattachitra Painting",
  "Phad Painting",
  "Miniature Painting",
  "Gond Art",
  "Sanjhi Art",
  "Block Printing",
  "Handloom Weaving",
  "Embroidery",
  "Jewelry Design",
  "Terracotta Art",
  "Pottery",
  "Clay Modeling",
  "Glass Painting",
  "Street Art",
  "Graffiti",
  "Origami",
  "Paper Crafting",
  "Shadow Puppetry",
  "Light Painting",
  "Choreography",
  "Makeup Artistry",
  "Body Painting",
  "Cosplay Design",
  "Prop Making",
  "Set Design",
  "Others"
];

export default INTERESTS;