const PROFESSIONS = [
  "Musician",
  "Singer",
  "Dancer",
  "Painter",
  "Sketch Artist",
  "Flutist",
  "Guitarist",
  "Violinist",
  "Pianist",
  "Photographer",
  "Actor",
  "Writer",
  "Poet",
  "Calligrapher",
  "Sculptor",
  "Tattoo Artist",
  "Graphic Designer",
  "Fashion Designer",
  "Interior Designer",
  "Animator",
  "Filmmaker",
  "Theater Artist",
  "Digital Artist",
  "Classical Dancer",
  "Rangoli Artist",
  "Mehndi Artist",
  "Warli Painter",
  "Madhubani Painter",
  "Jewelry Designer",
  "Terracotta Artist",
  "Potter",
  "Choreographer",
  "Makeup Artist",
  "Set Designer",
  "Voice Actor",
  "Storyteller",
  "Illustrator",
  "Handloom Weaver",
  "Screenwriter",
];

export default PROFESSIONS;
